title: Articles
description: Articles
author: Burak Koray Kose
github: https://github.com/burakkoray
about: Hi, I’m Burak Koray. I’m a developer from Istanbul. Here, I share my experiences with several technologies on mobile app development.
disqus_shortname: mobileDevelopment
google_analytics: UA-XXXXXXXX-Y
profile_image: https://media-exp1.licdn.com/dms/image/C4D03AQHUFVTj_namkg/profile-displayphoto-shrink_400_400/0?e=1596067200&v=beta&t=adKct2RUHZ4KA2wD8Eb4REfB4EfaC1aVEgrJW9H-x2g

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-twitter
      link: "https://twitter.com/burakkoray"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/burakkoraykose/"
    - icon: fa-stack-overflow
      link: "https://stackoverflow.com/users/3956401/burak-koray-k%c3%b6se"
    - icon: fa-github
      link: "https://github.com/burakkoray"

share:
  twitter_username: https://twitter.com/burakkoray

urls:
    - text: About Me
      url: /about/
    # - text: My Projects
    #   url: /projects/

url: "https://agusmakmun.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
